---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: 00:00
    assignees:
      - iamtheantitwink
      - dgmjr
    commit-message:
      include: scope
      prefix: "[docker]"
    rebase-strategy: auto
    labels:
      - dependabot
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: 00:00
    assignees:
      - iamtheantitwink
      - dgmjr
    commit-message:
      include: scope
      prefix: "[github-actions]"
    rebase-strategy: auto
    labels:
      - dependabot
